version: '3'
services:
    # Controller and agent are run from inside the boardfarm container
    controller:
        image: registry.gitlab.com/prpl-foundation/prplmesh/prplmesh-runner:${CI_PIPELINE_ID}
        privileged: true    # For the creation of the bridge to work
        container_name: controller
        environment:
            - USER=$USER
            - INSTALL_DIR=$ROOT_DIR/build/install
            - ROOT_DIR=$ROOT_DIR
            - CURRENT_ID=$CURRENT_ID
        expose:
            - "5000"
            - "8002"
        volumes:
            - "$ROOT_DIR:$ROOT_DIR"
        entrypoint: ["/root/entrypoint.sh", "/usr/bin/start-controller-agent"]

    agent:
        image: registry.gitlab.com/prpl-foundation/prplmesh/prplmesh-runner:${CI_PIPELINE_ID}
        privileged: true
        container_name: agent
        environment:
            - USER=$USER
            - INSTALL_DIR=$ROOT_DIR/build/install
            - ROOT_DIR=$ROOT_DIR
            - CURRENT_ID=$CURRENT_ID
        expose:
            - "5000"
            - "8002"
        volumes:
          - "$ROOT_DIR:$ROOT_DIR"
        entrypoint: ["/root/entrypoint.sh", "/usr/bin/start-agent"]

    # Boardfarm image is launched from dctest.py, TARGET_DIR refers to the
    # path inside the controller, will be referred as $ROOT_DIR inside
    boardfarm:
        build: .
        privileged: true
        container_name: boardfarm
        environment:
            - USER=$USER
            - ROOT_DIR=$ROOT_DIR
            - CURRENT_ID=$CURRENT_ID
            - RUN_ID=$RUN_ID
        ports:
            - "5000:5000"
        volumes:
            - "$ROOT_DIR:$ROOT_DIR"
            - "/var/run/docker:/var/run/docker"
            - "/var/run/docker.sock:/var/run/docker.sock"
        # user: ${CURRENT_UID}
        working_dir: $ROOT_DIR/tests
        entrypoint: ["bash", "run_bf_compose.sh"]
